name: Go

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_call:

env:
  # Version of Go to be used for builds
  GO_VERSION: '>=1.19'
  # Base directory in which to perform checkout, build and tests
  BASE_DIRECTORY: ./reg-room-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ env.BASE_DIRECTORY }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: Build
        working-directory: ${{ env.BASE_DIRECTORY }}
        run: go build -v ./...

      - name: Test
        working-directory: ${{ env.BASE_DIRECTORY }}
        run: go test -v ./...
