name: Go

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_call:

env:
  GO_VERSION: 1.19
  BASE_DIRECTORY: ./reg-room-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ env.BASE_DIRECTORY }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: go build -v ./...
        working-directory: ${{ env.BASE_DIRECTORY }}

      - name: Test
        run: go test -v ./...
        working-directory: ${{ env.BASE_DIRECTORY }}
