name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  call_build_test:
    uses: ./.github/workflows/go.yml

  call_release:
    needs: call_build_test
    uses: Fenrikur/reg-workflows/.github/workflows/release-go.yml@main
    with:
      archive-base-name: reg-room-service
      additional-artifacts: README.md LICENSE docs/config-template.yaml api/openapi-spec/openapi.yaml
